spring.application.name=OnlineLibrary

spring.datasource.url=jdbc:postgresql://dpg-d6nepti4d50c73dgm6t0-a.frankfurt-postgres.render.com/database2_6fc6
spring.datasource.username=database2_6fc6_user
spring.datasource.password=NOoDjGbnMqWHfxsFQ8DLHzvIxbz2Lawf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.sql.init.mode=always